### ISSUE TITLE
Interface admin en anglais seulement

### ISSUE THREAD

**Issue by LuluTchab** [epfl-idevelop/jahia2wp#116]
Issue ouverte dans JahiaP, déplacement à la main ici... voilà l'historique

@Escapevelocitycham
> L'interface des sites est en anglais. Normalement dans Settings > General, il est possible de modifier cette valeur et de choisir une autre langue ... sauf quand Polylang est activé !
> Dans le user profile, le choix de la langue a tout simplement disparu.
> 
> Voici un extrait de l'aide de Polylang : it [le menu Polylang] has no influence on the language of the 
> user admin interface, which can be chosen in the user profile.
>
> Contrôlé sur un site perso de @LuluTchab ... Polylang n'empêche pas de choisir la langue de l'interface ...
> Hypothèse de Lulu : l'image de wp que l'on utilise est américaine et on n'a pas les fichiers de langues ...

@LuluTchab

> Je ne me souviens plus de ce qu'on a mis pour `wp core download` en tant que paramètres mais on peut mettre une `locale`, peut-être que ça pourrait aider... et à voir si on entre en ligne de compte là-dessus. Le PO pourra le dire ^^
> La doc de `wp core download`: https://developer.wordpress.org/cli/commands/core/download/
> 
> Il y a d'ailleurs une option `--skip-content` pour ne pas télécharger les thèmes/plugins par défaut. Ceci pourrait être bien pour nous du fait que de toute façon, on efface ces trucs durant l'installation... ça permettrait de simplifier
> 
> Pour ce qui est le problème du timezone, il faudrait probablement passer la locale en plus dans la fonction `install_wp()` du fichier `generator.py` (paramètre à la fonction `wp config create`).
> 
> Et vu que ça fait 2 commandes pour lesquelles on aurait pu mettre des paramètres supplémentaires dès le début, peut-être qu'on pourrait regarder si y'a pas d'autres trucs qu'on aurait pu oublier (paramètres) sur les autres commandes WPCLI et qui pourraient nous faciliter la vie.

**Comment by lboatto** [comment]
C'est corrigé et mergé dans la master
