### ISSUE TITLE
Remove SSL from httpd to use edge termination in Openshift

### ISSUE THREAD

**Issue by dabelenda** [epfl-idevelop/jahia2wp#138]
This will allow:
* more metrics to be collected with the HAProxy (better traceability of requests).
* better performance (less CPU usage) since currently the SSL is performed at the level of the httpd host, while it will be offloaded to the HAProxy host (less operations on the httpd host means more CPU time for application)

To enable SSL offloading wordpress configuration needs to be configured to read X-Forwarded-Proto Header and Openshift route needs to be in edge termination mode.

**Comment by dabelenda** [comment]
In Wordpress wp-config.php to read X-Forwarded-Proto you can set:

```
if ($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https'){
       $_SERVER['HTTPS']='on';
}
```

**Comment by dabelenda** [comment]
We are doing tests on our side and make a PR later.

**Comment by dabelenda** [comment]
Hello we tested it, it works no issue, however making a PR is too hard since it is not simple to use wp-cli to add this code in the wp-config.php thus it will be on you to decide how you want to do it.

Generally the **--extra-php** option of wp-cli is used... but it takes the code from STDIN see: https://developer.wordpress.org/cli/commands/config/create/#options

After this addition to the config is done we can change the Routes and then cleanup the httpd image (removing of HTTPS in httpd).

**Comment by ebreton** [comment]
Hi @dabelenda , 

Could you clarify the change please? I am a bit lost on what piece of the structure encrypts/decrypts HTTP to/from HTTPS

What I understood so far, is the following, which is probably not accurate since it looks like there is plain HTTP between SLB and openshift
```
final user <-> DIODE <->    SLB     <->  OPENSHIFT   <->      HTTPD
  HTTPS    <->  ...  <-> HTTPS/HTTP <->  HTTP/HTTPS  <->    HTTPS/HTTP
                       EPFL certificate             self-signed certificate
```

**Comment by dabelenda** [comment]
currently:
```
final user <-> DIODE <-> SLB <-> Openshift Router <-> httpd
<---------- HTTPS----------> <------------- HTTPS -------------->
  *.epfl.ch Quovadis cert    |     Random self-signed cert
```
So the Openshift Router sees *nothing* cannot log and we do not know from where the client connect.

After this change:
```
final user <-> DIODE <-> SLB <-> Openshift Router <-> httpd
<----------- HTTPS-----------> <--- HTTPS ---><--- HTTP --->
  *.epfl.ch Quovadis cert    | self-signed Cert |   plaintext
```

No SSL processing at the httpd stage, so more CPU time for the application, the Openshift Router sees the content, so can log what happens, and if needed can perform sticky sessions.

**Comment by dabelenda** [comment]
The PR #140 is a discovery from the tests we made.
It actually makes you hit an issue with IP Restriction in httpd configuration (i.e. the IP restriction cannot work).

**Comment by ebreton** [comment]
Ok pour le schéma. C'est bien plus clair. On est donc en plaintext derrière openshift. Est ce qu'il fonctionne comme Rancher avec de l'IPsec ? Quelles sont les garanties qu'on ne se fasse pas sniffer le traffic avant d'arriver au Wordpress ?

**Comment by dabelenda** [comment]
OpenShift ne fait pas de tunnels IPSEC entre les noeuds.
Dans notre cas, on se base donc sur la sécurité du réseau, qui se trouve être un VLAN dédié avec un subnet privé en 10.180.21.0/24 donc on pense qu'il n'y a pas de problème. Si tu veux être sûr tu peux aller demander à l'équipe réseau ce qu'elle en dit.

**Comment by ebreton** [comment]
Hello @dabelenda , nous avons mergé PR #140 
Que reste-t-il à faire pour cette issue ?

En ce qui concerne la sécurité, je laisse à @jaepetto le dernier mot 😄

**Comment by dabelenda** [comment]
Hello,
Il faut mettre en place le bout de configuration dans Wordpress qui prend en compte le header X-Forwarded-For 

Pour rappel c'est ça:
```
if (isset( $_SERVER['HTTP_X_FORWARDED_PROTO'] ) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https'){
       $_SERVER['HTTPS']='on';
}
```

Avec cette configuration, le apache httpd n'a plus besoin d'écouter en HTTPS pour que Wordpress sache si oui ou non le client est arrivé en HTTP ou HTTPS sur le site web.

Pour info, si apache httpd écoute en HTTPS et que le client arrive en HTTPS sur apache, le serveur web (pour être exact mod_php) set la variable $_SERVER['HTTPS']=on et Wordpress utilise cette variable pour les redirections, les liens, etc. Donc cette configuration fait en sorte que la variable soit mise dans la configuration Wordpress et plus par le serveur web donc le serveur web n'a plus besoin d'écouter en HTTPS.

C'est une étape nécessaire avant de retirer le HTTPS entre les routeurs OpenShift et le pod, sinon vos clients auront du mixed-content et probablement d'autres problèmes de redirection HTTP->HTTPS.

**Comment by ebreton** [comment]
Hello @dabelenda , après discussion avec l'équipe et Manu, nous souhaitons continuer de travailler en HTTPS sur toute la ligne jusqu'au httpd. 

Pour nous, l'économie sur la consommation CPU ne justifie pas le passage en plaintext.

Nous sommes cependant conscients que ca offusque les logs, vous pourriez peut-êre décrypter + ré-encrypter au niveau du routeur openshift ? (ce qui rajoute du CPU, à vous de voir si l'analyse des logs en vaut le coup)

**Comment by mbornoz** [comment]
Hello @ebreton, pour nous non-plus l'économie CPU n'est pas le point principal, c'est plutôt le fait d'avoir un point d'extraction/observabilité commun (au niveau des routeurs) pour tous les projets qui seront hébergés sur cette plateforme. Dans l'urgence de cette mise en production on avait pas bien mesuré cette problématique qui en plus nous empêchera, à terme et si besoin, de faire du routage http par chemin.  Bref, c'est très frustrant au niveau opérationnel de ne pas avoir plus de visibilité sur ces routeurs haproxy. J'insiste sur le fait que nous nous rencontrions pour en discuter et que chacun puisse faire valoir ses arguments.

Merci à l'avenir de ne pas utiliser Github pour ce genre d'échanges, je passe le mot également de notre côté.

**Comment by ebreton** [comment]
test en cours sur https://wp5-os-exopge.epfl.ch/site10/ (et site11)

j'assigne le ticket à @Escapevelocitycham qui les prend en charge

**Comment by domq** [comment]
On dirait que c'est résolu ?
