### ISSUE TITLE
Les Wordpress créés en mode folder sont case-sensitive

### ISSUE THREAD

**Issue by ebreton** [epfl-idevelop/jahia2wp#143]
Par exemple, si on crée le site avec `https://env-lv-os-exopge.epfl.ch/tmp2/`, l'accès à `https://env-lv-os-exopge.epfl.ch/TMP2/` retourne une erreur

**Comment by LuluTchab** [comment]
Bah c'est comme ça que le web fonctionne, pour moi c'est une manière normalede fonctionner...
Du coup, est-ce qu'on "force" tout en minuscules? donc si c'est mis en majuscules dans la SV, on met en minuscule.

**Comment by ebreton** [comment]
oui on peut faire un `lower()` sur l'url que nous recevons (c'est déjà ce qu'on fait pour d'autres colonnes)

**Comment by ebreton** [comment]
pour compléter la discussion que nous avions au daily, Wordpress s'arrange pour rendre l'URL des pages un-sensitive, par exemple:

- https://dcsl-next.epfl.ch/index-html/page-126135-en-html/
- https://dcsl-next.epfl.ch/index-html/PaGe-126135-en-html/

fonctionnent de manière identique

**Comment by ebreton** [comment]
[Piste 1](https://stackoverflow.com/questions/46698037/how-to-make-this-url-case-insensitive) de stackoverflow

```
RewriteEngine On
RewriteMap lowercase int:tolower
RewriteCond %{REQUEST_URI} [A-Z] ##So that this rule is applied only if there's an Upper case in URI.
RewriteRule ^/(.*)$ /${lowercase:$1}

This should work.

Note - 'lowercase' is just a variable name and can be anything.
```

**Comment by LuluTchab** [comment]
Attention avec les 2 solutions proposées car ça prend en charge la totalité de l'URL alors que ça devrait théoriquement uniquement prendre en compte le nom du site (dossier contenant le site).
Si on transforme la totalité de l'URL et que pour une raison X ou Y un admin créé une page avec une majuscule dans le slug, bah il aura que des 404 dessus...

**Comment by ebreton** [comment]
Après discussion de l'équipe avec C2C, nous retenons la solution Varnish.

Nous allons le mettre en place dans le cadre du cache. Nous ajouterons alors une règle pour qu'il passe les URLs en lowercase. 

Par ailleurs, les URLs des sites passés dans la source de vérité sont également passés en lowercase depuis la PR #158
