### ISSUE TITLE
Cannot connect to wp-manager.epfl.ch

### ISSUE THREAD

**Issue by dragonleman** [epfl-idevelop/jahia2wp#146]
Compte : Lindo Duratti (DevRun)
Quand je clique sur "Connexion" :

Error communicating with Tequila, status is 403

**Comment by ebreton** [comment]
Même erreur constatée avec mon compte quand je génère un nouveau site (en l'occurence https://formation-wp.epfl.ch sur l'environnement de dev)

**Comment by lboatto** [comment]
L'erreur était du côté Tequila, c'est corrrigé.
