### ISSUE TITLE
Lien source des images en http => "not secure" (pas de cadenas vert)

### ISSUE THREAD

**Issue by obieler** [epfl-idevelop/jahia2wp#151]
**Exemple:**
**url:** https://help-wordpress.epfl.ch/pour-debuter/interface-dedition/

----------------------------------------------------------
![selection_125](https://user-images.githubusercontent.com/24526380/33766445-bc0167fc-dc1d-11e7-856d-4258c6bd7269.jpg)

**Comment by ebreton** [comment]
Le site a été créé en http...

![capture d ecran 2017-12-11 a 15 56 51](https://user-images.githubusercontent.com/490665/33837251-0e112e9a-de8c-11e7-83ca-044adfa51362.png)

Pour bien faire, il faut utiliser le plugin "better search replace" et remplacer l'URL avec sa version https... Je nous rajoute un post-it pour voir comment on l'inclut dans notre build. Si trop long d'automatiser, on le fera à la main sur ce site

**Comment by ebreton** [comment]
Site help-wordpress corrigé.

La PR #160 de Lucien corrigera les sites nouvellement créés.
