### ISSUE TITLE
The unit name SPRING doesn't exist

### ISSUE THREAD

**Issue by williambelle** [epfl-idevelop/jahia2wp#161]
```
Traceback (most recent call last):
  File "/srv/subdomains/jahia2wp/src/veritas/validators.py", line 93, in validate_unit
    get_unit_id(unit_name)
  File "/srv/subdomains/venv/lib/python3.5/site-packages/epflldap/ldap_search.py", line 70, in get_unit_id
    return response[0]['attributes'][attribute][0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jahia2wp.py", line 264, in <module>
    dispatch(__doc__)
  File "/srv/subdomains/venv/lib/python3.5/site-packages/docopt_dispatch.py", line 34, in __call__
    function(**self._kwargify(arguments))
  File "jahia2wp.py", line 172, in generate_many
    theme_faculty=row["theme_faculty"],
  File "/srv/subdomains/jahia2wp/src/wordpress/generator.py", line 59, in __init__
    self.validate_mockable_args(wp_site_url, unit_name)
  File "/srv/subdomains/jahia2wp/src/wordpress/generator.py", line 271, in validate_mockable_args
    validate_unit(unit_name)
  File "/srv/subdomains/jahia2wp/src/veritas/validators.py", line 95, in validate_unit
    raise ValidationError("The unit name {} doesn't exist".format(unit_name))
django.core.exceptions.ValidationError: ["The unit name SPRING doesn't exist"]
```

**Comment by LuluTchab** [comment]
Le problème provient du fait que la recherche LDAP est "simplement" faite avec `cn=SPRING` et en l'occurrence, ça renvoie 4 résultats...
- Un élément avec `objectclass=automount` : cn=spring,ou=auto.home,ou=automaps,o=epfl,c=ch
- Un groupe défini sur http://groups.epfl.ch (cn=spring,ou=groups,o=epfl,c=ch) avec `objectclass=[groupOfNames, EPFLGroupOfPersons]` 
- Une personne (cn=Ivan Christophe Spring,ou=dii-e,ou=rho-dii,ou=rho,o=epfl,c=ch) avec `objectclass=[swissEduPerson, person, organizationalPerson, EPFLorganizationalPerson, inetOrgPerson, posixAccount, shadowAccount]`
- L'unité que l'on cherche (ou=spring,ou=iinfcom,ou=ic,o=epfl,c=ch) avec `objectclass=[posixGroup, EPFLorganizationalUnit, organizationalUnit]`

C'est donc le 4e élément que l'on cherche. Mais par défaut, le code de @GregLeBarbar cherche dans le premier élément renvoyé et tente de retourner l'attribut "uniqueIdentifier" (qui n'existe pas pour un élément `automount`). 
Donc, il faudrait améliorer le code du package `epfl-ldap` pour ajouter un filtre sur un autre champ (peut-être `objectclass`, ou un autre, voir avec Claude ou Charles-François) histoire d'être sûr de ne chercher QUE les unités, pas qu'on reçoive potentiellement autre chose.

Je me permet d'assigner à @GregLeBarbar du fait que c'est lui qui a fait le package à l'origine :-D

**Comment by GregLeBarbar** [comment]
La version 0.0.6 de la librairie [epfl-ldap](https://github.com/epfl-idevelop/epfl-ldap) a corrigé le problème
