### ISSUE TITLE
[8] Installer un WP avec les plugins sélectionnés lors du proto

### ISSUE THREAD

**Issue by ebreton** [epfl-idevelop/jahia2wp#34]
En tant que **webmaster**, je veux disposer des plugins présentés et installés lors de la phase de prototypage pour disposer de plus de fonctionnalités que celles présentes dans un WP nu.

Polylang est adressé dans une histoire à part. Les plugins concernés sont les suivants :

- add-to-any
- BasicAuth
- black-studio-tinymce-widget
- tinymce-advanced
- epfl_infoscience

## Acceptance tests

- les plugins listés ci-dessus sont installés, configurés et activés

**Comment by LuluTchab** [comment]
Etat des tests d'utilisation de WPCLI pour la configuration ici : https://confluence.epfl.ch:8443/x/tIpLAw

**Comment by ebreton** [comment]
questions complémentaires ajoutées sur la dite page 👍
