### ISSUE TITLE
WP_ENV non initialisé si fresh install

### ISSUE THREAD

**Issue by LuluTchab** [epfl-idevelop/jahia2wp#43]
Il a dû y avoir un changement dans le fichier ".env" car avant il était dans le dossier "local/" et il contenait une ligne "WP_ENV=..."
Maintenant, le fichier ".env" est à la racine du repository mais cette ligne a disparu. Du coup comme la variable "WP_ENV" n'est pas définie en local (dans .bashrc), c'est la valeur qui est dans "Makefile" qui est prise par défaut.

**Comment by ebreton** [comment]
le répertoire local a disparu effectivement avec la nouvelle composition docker. Et le fichier .env est à la racine du projet.

La variable WP_ENV pour sa part est également sortie du fichier .env pour devenir une "vraie" variable d'environnement. Obligatoire. Elle est définie dans ton .bashrc par le bootstrap-local si elle n'est pas settée dans ton environnement.

Je pense que tes soucis viennent du fait que tu "migres" de l'état précédent vers le nouveau. On regarde ensemble si tu es bloqué. Ca sera plus simple
