### ISSUE TITLE
Option "clean-one" n'efface pas tout

### ISSUE THREAD

**Issue by LuluTchab** [epfl-idevelop/jahia2wp#45]
Les fichiers commençant par "." (comme .htaccess) ne sont pas effacés par la fonction.

Pas testé si c'était la même chose pour les dossiers par contre.

**Comment by ebreton** [comment]
Yes, c'est juste. le script utilise un système de "white list" pour effacer le contenu. L'objectif étant de controler précisément ce qui est supprimé (et d'éviter les mauvaises surprises)

WP_DIRS pour les répertoires et WP_FILES pour les fichiers sont définis dans le fichier de [settings](https://github.com/epfl-idevelop/jahia2wp/blob/f7ff2968fbabf8ed42e996517dc23c844618ca14/src/settings.py#L17)

Si nous conservons cette logique, il faut rajouter le '.htaccess' dans WP_FILES. Mais je suis ouvert à d'autres idées :)

**Comment by LuluTchab** [comment]
Corrigé, meurdjé
