### ISSUE TITLE
Check GA et Cookie disclaimer

### ISSUE THREAD

**Issue by ebreton** [epfl-idevelop/jahia2wp#95]
Hello le DevRun !

Nous utilisons le header reponsive sur nos sites wordpress (grâce à l'aide de William dans https://github.com/epfl-idevelop/jahiap/issues/280)

Pouvez vous nous confirmer que le header
- inclue le tag Google Analytics
- inclue le disclaimer pour l'utilisation de cookie

Nous n'avons d'ailleurs jamais vu ce disclaimer. Est ce qu'il y a quelque chose à faire pour le faire apparaitre ?

**Comment by ebreton** [comment]
Hello William !

J'ai construit un site sur un nouveau sous-domaine hier sans avoir le disclaimer. As-tu une issue ouverte pour cette correction? que nous puissions suivre et tester ?

++
Manu

**Comment by williambelle** [comment]
Hello,

J'avais corrigé et déployé. J'ai testé ici :

![screenshot](https://user-images.githubusercontent.com/2843501/33229363-cf09f42c-d1cd-11e7-9ef9-be657c1e9069.png)

Le JavaScript `epfl-jquery-built.js` pointe vers la version latest donc attention au cache.

**Comment by ebreton** [comment]
effectivement, ça marche bien sans cache 🎈 

@williambelle : j'ai également checké le compte GA utilisé, j'ai trouvé "UA-1244922-8" dans la page. C'est juste ?

Dans l'interface google analytics, j'ai un compte différent : "UA-4833294-1"

Qu'est ce qui est correct ?



Merci !

**Comment by williambelle** [comment]
Le tracker du bandeau est : "UA-4833294-1". Il est définit ici : https://github.com/epfl-idevelop/kis-bootstrap/blob/d6518a4aa0bf990d9a44e43209d3ed9ce0566f89/app/scripts/plugins/analytics.coffee#L39

J'ai aussi trouvé le "UA-1244922-8". Il est dans l'iframe du plugin AddToAny. Je crois pas qu'on a de contrôle là dessus ?

![screenshot](https://user-images.githubusercontent.com/2843501/33231423-955f23aa-d1f5-11e7-842b-d23986b2ac8f.png)

**Comment by ebreton** [comment]
ok, on est bon pour notre compte. 

En ce qui concerne celui de AddToAny, nous n'avons effectivement pas le contrôle, et c'est une (bonne) question pour @jaepetto : est ce que le disclaimer est suffisant pour couvrir les deux tracking (le notre et celui de AddToAny) ?

**Comment by ebreton** [comment]
Après discussion, nous allons désactiver le plugin AddToAny. J'ai créé l'issue #119 pour trouver un remplaçant sans tag google analytics

**Comment by ebreton** [comment]
retiré de la liste des plugins installés par défaut dans PR #117
